### ISSUE TITLE
Need to set Project tracking's default as it is described in Preset description

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#574] opened 2018-06-10 07:57 UTC
Right now, when adding tracking on a project that has a Preset description, the default is _Development_ instead of what described in the preset

![edit_project_unfpa_global__hq____live_gizra_productivity](https://user-images.githubusercontent.com/7068965/41199496-d51fa186-6c9b-11e8-8f45-f33c52fc979e.png)

When trying to report a Code/Issue Review, the defalt is _Development_  and not  _Code/Issue Review_ 

![live_gizra_productivity](https://user-images.githubusercontent.com/7068965/41199521-494eabe2-6c9c-11e8-8467-f054ff298624.png)

**Comment by OritGeron** [comment] 2018-06-10 07:58
@noamoss  Please pay attention until it fixed

**Comment by noamoss** [comment] 2018-06-10 08:04
@OritGeron 👍 let's fix manually to "senior qa" once @nedSaf fixes that.

**Comment by RachelBaram** [comment] 2018-06-10 08:22
@nedSaf It looks like this only happens for tracking items that are automatically triggered.

**Comment by OritGeron** [comment] 2018-06-10 08:26
@RachelBaram it's happening on manual tracking as well

**Comment by nedSaf** [comment] 2018-06-11 06:14
@OritGeron @noamoss @RachelBaram Ready for your check on `live`

**Comment by nedSaf** [comment] 2018-06-11 06:15
@OritGeron Please close if ok.

**Comment by OritGeron** [comment] 2018-06-11 07:30
@nedSaf you are awesome!

**Comment by LudmilaGoichman** [comment] 2018-06-19 09:12
@nedSaf 

- 19/06/18

**Can't see the correct dropdown list for projects in Gira (UNFPA Global and Offices):**

Expected (from Orit's computer; After the project selection):
![pasted_image_19_06_2018__12_11](https://user-images.githubusercontent.com/35059802/41588248-e923743a-73b9-11e8-9832-ea16ecb367db.jpg)

Current (on my comp; After the project selection):
![live_gizra_productivity_and_slack_-_gizra](https://user-images.githubusercontent.com/35059802/41588207-d37bdf3c-73b9-11e8-9379-7c5395996808.jpg)

**Comment by OritGeron** [comment] 2018-06-19 11:12
@nedSaf I noticed @amaksimov also experiencing the same issue
![live_gizra_productivity](https://user-images.githubusercontent.com/7068965/41594040-b3cf1db4-73ca-11e8-851e-dde6cc85ebe1.png)

**Comment by nedSaf** [comment] 2018-06-19 14:38
@LudmilaGoichman @OritGeron I can't reproduce it, every time I select one of the 2 projects:
- UNFPA GLOBAL (HQ)
- UNFPA YPS

I get the pre-set descriptions:
![live_gizra_productivity](https://user-images.githubusercontent.com/7369740/41604180-4c9c6e40-73e7-11e8-900e-7f98913a14be.png)

I tried multiple times, Maybe someone changed the content and revert it back.
Please make sure you are looking at the right project. closing this issue, If you still have an issue, please contact me and let's try to reproduce together then we can open a new issue.

Please don't comment on closed issues.

**Closed by nedSaf** 2018-06-19 14:38 UTC
Labels: Bug, Deployed Live, Merged
